apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: localhpatest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctsdeploy
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 40
      type: Resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctsdeploy
spec:
  selector:
    matchLabels:
      app: cts
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                  
    rollingUpdate:
      maxUnavailable: 1                                  
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cts
    spec:
      nodeSelector:
        os: windows
      containers:
      - name: myaccesscontainer
        image: acrdevopspoc.azurecr.io/cognizantdevops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits: 
              cpu: "100m"
              memory: "256Mi"
      imagePullSecrets:
      - name: myaccess1
---   

apiVersion: v1
kind: Service
metadata:
  name: ctsservice
  labels:
    app: cts
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cts