apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: localhpatest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cognizant_deploy
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 40
      type: Resource
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cognizant_deploy
spec:
  selector:
    matchLabels:
      app: CTS
  replicas: 2
  template:
    metadata:
      labels:
        app: CTS
    spec:
      containers:
      - name: CTS_Container
        image: acrdevopspoc.azurecr.io/cognizantdevops:$(Build.BuildNumber)
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits: 
              cpu: "100m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cognizant_service
  labels:
    app: CTS
spec:
  type: LoadBalancer
  ports:
  - port: 83
    protocol: TCP
    targetPort: 80
  selector:
    app: CTS